CREATE TABLE [dbo].[ProjectGroup] (
    [Id]   NVARCHAR (50)  NOT NULL,
    [Name] NVARCHAR (200) NOT NULL,
    [JSON] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_ProjectGroup_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_ProjectGroupNameUnique] UNIQUE NONCLUSTERED ([Name] ASC)
);

